### ISSUE TITLE
todos and impl

### ISSUE THREAD

**Issue by ycw** [ycw/svg-path#1]
## Todos

Lexer errs
- [x] unrecognized `M 0 ; 0 `
- [x] not begin w/ moveto `Z`
- [x] begin w/ comma `  , M 0 0`
- [x] end w/ comma `M 0 0 L 0 0 ,`
- [x] cmd followed by comma `M , 0 0`
- [x] cmd follows comma `M 0 0 , L 0 0`
- [x] consecutive commas `M 0 ,, 0`
- [x] too few params `M 0`
- [x] num is not param `M 0 0 Z 0`
- [x] flag is not 0 or 1 `A 0 0 0 3 0 0 0`
- [x] radius is negative `A -1 0 0 0 0 0 0`
- [x] trailing dot `M 0. 2`

Lexer opts
- [x] no trailing dot  

Parser 
- [x] accept lexer's output .. as input
- [x] accept path data ( in string ) .. as input

Transformer fns
- [x] normalize ( into all abs cmd )
- [x] reframe ( remap coords )

Generator opts
- [x] multiline ( ex `"M 0 0\nH 1"` )
- [x] decimal places ( `M 0 0.6666..` -> `"M 0 0.67"` )
- [x] combine ( `Segs [ M L L ]` -> `"M x y x y x y"` )

## Impl

let d be path data in string

1. `tokenize ( d )` -> arr of tokens  ... # tks `Tk[]`
2. `analyze ( tks )` -> arr of instructions ... # instrs `[ Tkcmd, Tknums[] ][]` 
3. `parse ( instrs )` -> arr of path segments ... # segs `Seg { ty , pars } []`
4. `transform ( segs )` -> new arr of segs ... # segs'
5. `generate ( segs' )` -> path data in string
